completed css-layout-classes
moamel97/c1021-code-solutions pull request #18
Opened 2021-10-08 02:32 UTC by moamel-hashim

![image](https://user-images.githubusercontent.com/90476994/136488981-c15319cf-1247-47ea-9fba-a7d1569c01b1.png)

2021-10-08 16:14 UTC, codingcodymiller requested changes

2021-10-08 16:14 UTC, codingcodymiller commented on css-layout-classes/styles.css
> +}
Where's the CSS for all your `column` classes? They should have a rule that sets their size to an appropriate measurement related to their name

2021-10-08 16:14 UTC, codingcodymiller commented on css-layout-classes/index.html
> +    <div>
No `column-one-third`? What size is this column meant to be?

2021-10-08 16:14 UTC, codingcodymiller commented on css-layout-classes/index.html
> +    <div class="character">
`character` is not a layout class, you should make a `column` class that accurately describes the size of these elements.

2021-10-08 16:14 UTC, codingcodymiller commented on css-layout-classes/index.html
> +    <div class="column-tow-third">
`column-two-third`

2021-10-08 16:14 UTC, codingcodymiller commented on css-layout-classes/index.html
> +    <div>
No column class?

2021-10-08 16:14 UTC, codingcodymiller commented on css-layout-classes/index.html
> +    <div>
No column class?

2021-10-08 22:36 UTC, moamel97 commented
![image](https://user-images.githubusercontent.com/90476994/136631662-81939cc9-08e5-4f78-af2f-d40416f18ccd.png)

2021-10-08 23:00 UTC, codingcodymiller requested changes

2021-10-08 23:00 UTC, codingcodymiller commented on css-layout-classes/styles.css
> +.character {
How about `column-one-fourth`? You should change the width to `25%` also

2021-10-11 05:37 UTC, moamel97 commented
![Capture](https://user-images.githubusercontent.com/90476994/136738460-63b8603e-6aa6-451a-a52d-3814ed991456.PNG)

2021-10-11 05:41 UTC, moamel97 commented
updated the width on .character class to 30% instead of 141%

2021-10-11 16:00 UTC, codingcodymiller commented on css-layout-classes/styles.css
> +}
There should be no need for an additional `row` class like this. In fact, as I've mentioned previously, the only styling that should be applied to the `row` class is `display: flex`. Anything beyond that should be applied to an additional class you can add along with `row` so that the `row` class can continue to be reused without making variants such as `.row2`

2021-10-11 16:01 UTC, codingcodymiller commented on css-layout-classes/styles.css
> +}
Again, there should only be one `row` class.

2021-10-12 06:36 UTC, moamel97 commented
![image](https://user-images.githubusercontent.com/90476994/136904333-5926579b-b6fc-46c8-8b08-fc45895dd6b2.png)
![image](https://user-images.githubusercontent.com/90476994/136904350-e51ef4af-ce35-4584-9ae1-d19ed0f3b3c6.png)

4th time is the charm

2021-10-12 16:07 UTC, codingcodymiller commented on css-layout-classes/index.html
> +      <div>
This element still needs an appropriate column class.

2021-10-12 16:07 UTC, codingcodymiller commented on css-layout-classes/index.html
> +      <div>
This element still needs an appropriate column class.

2021-10-12 16:07 UTC, codingcodymiller commented on css-layout-classes/index.html
> +      <div>
This element still needs an appropriate column class.

2021-10-12 16:07 UTC, codingcodymiller commented on css-layout-classes/index.html
> +      <div>
This element still needs an appropriate column class.

2021-10-12 16:07 UTC, codingcodymiller commented on css-layout-classes/index.html
> +      <div>
This element still needs an appropriate column class.

2021-10-12 16:07 UTC, codingcodymiller commented on css-layout-classes/index.html
> +      <div>
This element still needs an appropriate column class.

2021-10-12 16:07 UTC, codingcodymiller commented on css-layout-classes/index.html
> +      <div>
This element still needs an appropriate column class.

2021-10-13 04:57 UTC, moamel97 commented
![image](https://user-images.githubusercontent.com/90476994/137069940-b049f732-07b4-49d4-a6e1-6fc48bfec562.png)
![image](https://user-images.githubusercontent.com/90476994/137069973-1379154a-0ee6-4c94-be7e-eac8b1e50176.png)

2021-10-13 16:28 UTC, codingcodymiller commented on css-layout-classes/index.html
> +      <div class="column-full">
This is not `100%` width, so it's not `column-full`. Each of these takes up a fourth of the available width, so the appropriate class name would be `column-fourth`

2021-10-13 16:28 UTC, codingcodymiller commented on css-layout-classes/index.html
> +      <div class="column-full">
Please fix these as well

2021-10-15 06:37 UTC, merged