completed css-two-column-layout
moamel97/c1021-code-solutions pull request #21
Opened 2021-10-10 04:48 UTC by moamel97

![image](https://user-images.githubusercontent.com/90476994/136682601-48ed6c1f-1402-4712-87bf-6573f59a0320.png)

2021-10-12 04:59 UTC, moamel97 commented
heres the picture after i did the change 

![image](https://user-images.githubusercontent.com/90476994/136894170-4b7e4c15-a617-4636-90bc-4039d1a8e399.png)
![image](https://user-images.githubusercontent.com/90476994/136894220-afe36ea8-c4f6-40d4-935f-e3a3ef4b6f44.png)

2021-10-12 18:31 UTC, codingcodymiller requested changes

2021-10-12 18:31 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  margin-left: 12%;
Why is this necessary?

2021-10-12 18:31 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +.column-full {
The only styling on `column` classes should be either `flex-basis` or `width`, this includes other stuff. Instead of polluting your `column` class with that styling, you should make a separate class you can add to the element in addition to the `column` class.

2021-10-12 18:31 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  width: 53%;
Why are you setting a width on the image? Does that mean that the `column-half` element that is holding it is too big? You probably just need a smaller `column` class.

2021-10-12 18:31 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  margin-left: 41%;
_**WAY**_ too much margin. Why is this necessary?

2021-10-12 18:31 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  margin-left: 18%;
_**WAY**_ too much margin. Why is this necessary?

2021-10-13 07:35 UTC, moamel97 commented on css-two-column-layout/styles.css
> +  margin-left: 18%;
its necessary so it can push the button to the left a little bit so it can line up with text.

2021-10-14 04:41 UTC, moamel97 commented
![image](https://user-images.githubusercontent.com/90476994/137253185-905f878a-a58a-4d1b-93e8-031353a65dce.png)

2021-10-14 17:14 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +}
Instead of doing this to put space between these elements, you should either increase the width of your `container` class, or apply something like `padding` on your `column-half` elements.

2021-10-16 00:01 UTC, codingcodymiller requested changes

2021-10-16 00:01 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +.column-three-qurters {
`column-three-quarters`

2021-10-16 00:01 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  flex-direction: column;
Try removing the `display: flex` and `flex-direction: column`, they shouldn't be necessary

2021-10-16 00:01 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  display: flex;
Try removing the `display: flex` and `flex-direction: column`, they shouldn't be necessary

2021-10-25 00:28 UTC, merged