completed array manipulation 1
moamel97/c1021-code-solutions pull request #53
Opened 2021-11-01 07:11 UTC by moamel97

![Capture](https://user-images.githubusercontent.com/90476994/139634868-07a6b5f9-afb9-4df1-916f-7f27ef9aa1be.PNG)

2021-11-01 16:43 UTC, codingcodymiller requested changes

2021-11-01 16:43 UTC, codingcodymiller commented on array-manipulation-1/src/compact.js
> +  return arrayHolder;
Can you explain to me how this works?

2021-11-01 16:43 UTC, codingcodymiller commented on array-manipulation-1/src/head.js
> +  for(var i = 0; i < array.length; i++) {
This loop is unnecessary, you are retrieving one value at the `0` index, the loop here is doing nothing for you.

2021-11-01 16:43 UTC, codingcodymiller commented on array-manipulation-1/src/initial.js
> +    if (i < array.length -1) {
Instead of having this conditional in the loop, you can adjust your condition to stop sooner, and remove the need for this.

2021-11-01 16:43 UTC, codingcodymiller commented on array-manipulation-1/src/tail.js
> +    if (i > 0) {
Instead of having this conditional in the loop, you can adjust your initialization to start at `1` rather than `0`, and remove the need for this.

2021-11-01 16:43 UTC, codingcodymiller commented on array-manipulation-1/src/last.js
> +  for(var i = 0 ; i < array.length ; i++) {
This loop is unnecessary, you are retrieving one value at the last index of the array, you should just retrieve the length of the array and calculate the last index from it, then retrieve the value at that index.

2021-11-02 05:25 UTC, moamel97 commented
![image](https://user-images.githubusercontent.com/90476994/139791231-7c19ceb3-7294-4c3e-8c50-9b9d30a3dd4e.png)

updated array manipulation

2021-11-02 23:25 UTC, codingcodymiller approved these changes

2021-11-05 02:13 UTC, merged