completed html-forms
moamel97/c1021-code-solutions pull request #8
Opened 2021-10-05 22:50 UTC by moamel-hashim

![image](https://user-images.githubusercontent.com/90476994/136113345-4de11f78-4b7f-496f-9e8e-0308c568dd61.png)

2021-10-05 23:27 UTC, codingcodymiller requested changes
Great start! A few notes for you:

2021-10-05 23:27 UTC, codingcodymiller commented on html-forms/index.html
> +<label for="select">why is coding cool</label> <br>
This label is not configured correctly, make sure that the value of the `for` attribute matches the value of the `id` attribute on the `select` element this is correlated with

2021-10-05 23:27 UTC, codingcodymiller commented on html-forms/index.html
> +  <label for="favorite language (choose one)">Favorite Language (choose one)</label>
This isn;t labelling a specific input, so it doesn't need to be a `label`, it can just be a `p` element or something to that effect

2021-10-05 23:27 UTC, codingcodymiller commented on html-forms/index.html
> +    <input type="radio" name= "Language" id="javascript" value="javascript">JavaScript
The text next to each of these `input` elements should be a `label`

2021-10-05 23:27 UTC, codingcodymiller commented on html-forms/index.html
> +  <div>comments</div>
This should be a `label`

2021-10-05 23:42 UTC, moamel97 commented on html-forms/index.html
> +  <div>comments</div>
the comments ?

2021-10-06 16:18 UTC, codingcodymiller approved these changes

2021-10-11 00:59 UTC, merged